# Generated by Django 3.2.7 on 2021-10-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_related_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='related_workspace',
            new_name='workspace',
        ),
    ]
