# Generated by Django 3.2.7 on 2021-10-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_related_workspace_record_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='workspace',
        ),
    ]
