# Generated by Django 3.2.7 on 2021-10-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_groups', '0003_rename_related_workspace_genericgroup_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericgroup',
            name='workspace',
        ),
    ]
