# Generated by Django 3.2 on 2021-05-05 18:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphConditionalFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_color', models.CharField(max_length=64)),
                ('alert_color_threshold_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PreviewSettings',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='devices.device')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph_type', models.CharField(default='table', max_length=64)),
                ('device_data_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('from_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('to_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('start_offset_time', models.DurationField(blank=True, default=None, null=True)),
                ('aggregate_period_name', models.CharField(blank=True, max_length=32, null=True)),
                ('aggregate_operation_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('is_last_value', models.BooleanField()),
                ('device_data_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
                ('from_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('to_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('start_offset_time', models.DurationField(blank=True, default=None, null=True)),
                ('aggregate_period_name', models.CharField(blank=True, max_length=32, null=True)),
                ('aggregate_operation_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict)),
                ('devices', models.ManyToManyField(related_name='graphs', to='devices.Device')),
                ('groups', models.ManyToManyField(related_name='graphs', to='groups.Group')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
