# Generated by Django 3.2.7 on 2021-12-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_groups', '0006_alter_genericgroup_workspace'),
        ('settings', '0002_alter_settings_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='generic_groups',
            field=models.ManyToManyField(blank=True, to='generic_groups.GenericGroup'),
        ),
    ]
