# Generated by Django 3.2 on 2021-05-05 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAction',
            fields=[
                ('group_action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_action_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('group_action_name',),
            },
        ),
        migrations.CreateModel(
            name='GroupResource',
            fields=[
                ('group_resource_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_resource_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('group_resource_name',),
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('group_role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_role_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('group_role_name',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceAction',
            fields=[
                ('workspace_action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_action_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('workspace_action_name',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceResource',
            fields=[
                ('workspace_resource_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_resource_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('workspace_resource_name',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('workspace_role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_role_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('workspace_role_name',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceACL',
            fields=[
                ('workspace_acl_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.workspaceaction')),
                ('workspace_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.workspaceresource')),
                ('workspace_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.workspacerole')),
            ],
            options={
                'unique_together': {('workspace_role', 'workspace_action', 'workspace_resource')},
            },
        ),
        migrations.CreateModel(
            name='GroupACL',
            fields=[
                ('group_acl_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.groupaction')),
                ('group_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.groupresource')),
                ('group_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.grouprole')),
            ],
            options={
                'unique_together': {('group_role', 'group_action', 'group_resource')},
            },
        ),
    ]
