# Generated by Django 3.2 on 2021-05-05 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('settings', models.JSONField(blank=True, default=dict, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DashboardGroupRelationship',
            fields=[
                ('dashboard_group_relationship_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dashboard', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_groups', to='dashboards.dashboard')),
                ('group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_groups', to='groups.group')),
            ],
            options={
                'unique_together': {('dashboard', 'group')},
            },
        ),
        migrations.CreateModel(
            name='DashboardGraphRelationship',
            fields=[
                ('dashboard_graph_relationship_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_graphs', to='dashboards.dashboard')),
                ('graph', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_graphs', to='graphs.graph')),
            ],
            options={
                'unique_together': {('dashboard', 'graph')},
            },
        ),
        migrations.AddField(
            model_name='dashboard',
            name='graphs',
            field=models.ManyToManyField(related_name='dashboards', through='dashboards.DashboardGraphRelationship', to='graphs.Graph'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='groups',
            field=models.ManyToManyField(related_name='dashboards', through='dashboards.DashboardGroupRelationship', to='groups.Group'),
        ),
    ]
