# Generated by Django 3.2 on 2021-06-01 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, null=True)),
                ('user_id', models.CharField(max_length=64, null=True)),
                ('action_type', models.CharField(max_length=64)),
                ('modified_model_name', models.CharField(max_length=64)),
                ('modified_object_name', models.CharField(max_length=64)),
                ('modified_object_id', models.CharField(max_length=64, null=True)),
                ('modification', models.JSONField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('role_name', models.CharField(max_length=64, null=True)),
                ('workspace_name', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
