# Generated by Django 3.2.7 on 2021-10-17 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentconfig',
            name='related_workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='related_workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='environmentconfig',
            unique_together={('key', 'related_workspace')},
        ),
        migrations.RemoveField(
            model_name='environmentconfig',
            name='workspace',
        ),
    ]
