# Generated by Django 3.2.7 on 2021-12-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0012_alter_workspace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='db_connection',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
