# Generated by Django 3.2.7 on 2021-12-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_alter_workspace_db_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
