# Generated by Django 3.2.7 on 2021-12-25 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_disabled'),
        ('workspaces', '0014_workspace_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='icon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_icon', to='files.file'),
        ),
    ]
