# Generated by Django 3.2.7 on 2021-10-18 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_alter_workspace_db_connection'),
        ('users', '0008_userrolegenericgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroleworkspace',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace'),
        ),
    ]
