# Generated by Django 3.2.7 on 2021-12-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
