# Generated by Django 3.2.7 on 2022-02-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='informations',
            field=models.JSONField(blank=True, default='{}'),
        ),
    ]
