# Generated by Django 3.2 on 2021-05-05 18:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(blank=True, max_length=64)),
                ('invite_token', models.CharField(max_length=1000, unique=True)),
                ('custom_field', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='InviteGroupMembership',
            fields=[
                ('invite_group_membership_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_group_memberships', to='groups.group')),
                ('group_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_group_memberships_with_role', to='acl.grouprole')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_group_memberships', to='invites.invite')),
            ],
            options={
                'unique_together': {('invite', 'group')},
            },
        ),
        migrations.AddField(
            model_name='invite',
            name='groups',
            field=models.ManyToManyField(related_name='potential_members', through='invites.InviteGroupMembership', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='invite',
            name='workspace_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='acl.workspacerole', verbose_name="This invitees's potential role in the Workspace."),
        ),
    ]
