# Generated by Django 3.2 on 2021-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(blank=True, default='default', max_length=64),
        ),
    ]
