# Generated by Django 3.2 on 2021-05-05 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=128)),
                ('position', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('last_triggered_timestamps', models.JSONField(blank=True, default=None, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(related_name='devices', to='groups.Group')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
