# Generated by Django 3.2.7 on 2021-10-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20211017_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='related_workspace',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='related_workspace',
            new_name='workspace',
        ),
    ]
