# Generated by Django 3.2.7 on 2021-12-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_groups', '0006_alter_genericgroup_workspace'),
        ('authorization', '0006_auto_20211019_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='generic_groups',
            field=models.ManyToManyField(blank=True, to='generic_groups.GenericGroup'),
        ),
        migrations.AddField(
            model_name='role',
            name='generic_groups',
            field=models.ManyToManyField(blank=True, to='generic_groups.GenericGroup'),
        ),
    ]
