# Generated by Django 3.2.7 on 2021-12-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20211202_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
